/**
 * Auto-generated by scripts/fetch-gallery.mjs — do not edit by hand.
 * Real, freely-licensed photos downloaded from Wikimedia Commons for each
 * trek's detail-page gallery. Each array maps to files in public/images/gallery/.
 */
export const trekGalleries: Record<string, string[]> = {
    "sangestar-tso-madhuri-lake-loop": ["/Sangester.png", "/Sangester1.png", "/Sangester2.png", "/Sangester3.png", "/Sangester4.png", "/Sangester5.png", "/Sangester6.png", "/Sangester7.png", "/Sangester8.png", "/Sangester9.png"],
    "dong-valley-sunrise-trek": ["/DongValley.png", "/DongValley1.png", "/DongValley2.png", "/DongValley3.png", "/DongValley4.png", "/DongValley5.png", "/DongValley6.png", "/DongValley7.png", "/DongValley8.png", "/DongValley9.png"],
    "talle-valley-trek": ["/Ziro.png", "/Ziro1.png", "/Ziro2.png", "/Ziro3.png", "/Ziro4.png", "/Ziro5.png", "/Ziro6.png", "/Ziro7.png", "/Ziro8.png", "/Ziro9.png"],
    "gorichen-base-camp-trek": ["/Gorichen.png", "/Gorichen2.png", "/Gorichen3.png", "/Gorichen4.png", "/Gorichen5.png", "/Gorichen6.png", "/Gorichen7.png", "/Gorichen8.png", "/Gorichen9.png"],
    "bailey-trail-trek": ["/BaileyTrek.png", "/BaileyTrek2.png", "/BaileyTrek3.png", "/BaileyTrek4.png", "/BaileyTrek5.png", "/BaileyTrek6.png", "/BaileyTrek7.png", "/BaileyTrek8.png", "/BaileyTrek9.png"],
    "seven-lakes-trek-anini": ["/anini.png", "/anini1.png", "/anini2.png", "/anini3.png", "/anini4.png", "/anini5.png", "/anini6.png", "/anini7.png", "/anini8.png", "/anini9.png"],
    "monpa-culture-trek": ["/Sangester.png", "/Sangester1.png", "/Sangester2.png", "/Sangester3.png", "/Sangester4.png"],
    "lohit-valley-explorer": ["/DongValley.png", "/DongValley1.png", "/DongValley2.png", "/DongValley3.png", "/DongValley4.png"],
    "west-siang-river-trek": ["/Ziro.png", "/Ziro1.png", "/Ziro2.png", "/Ziro3.png", "/Ziro4.png"],
    "subansiri-alpine-pass": ["/Gorichen.png", "/Gorichen2.png", "/Gorichen3.png", "/Gorichen4.png", "/Gorichen5.png"],
    "kameng-river-gorge-trek": ["/BaileyTrek.png", "/BaileyTrek2.png", "/BaileyTrek3.png", "/BaileyTrek4.png", "/BaileyTrek5.png"],
    "changlang-tiger-reserve": ["/anini.png", "/anini1.png", "/anini2.png", "/anini3.png"],
    
};